const GET_POKEMONS = 'GET_POKEMONS'
const GET_POKEMON_BY_NAME = 'GET_POKEMON_BY_NAME'
const GET_POKEMON_BY_ID = 'GET_POKEMON_BY_ID'
const GET_TYPES = 'GET_TYPES'
const POST_POKEMON = 'POST_POKEMON'
const RESET = 'RESET'
const FILTER = 'FILTER'
const SORT_NAME = 'SORT_NAME'
const SORT_ATTACK = 'SORT_ATTACK'
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
const SET_ERROR = 'SET_ERROR'
const CLEAR_ERROR = 'CLEAR_ERROR'
const CLEAR_SUCCES = 'CLEAR_SUCCES'

export {
    GET_POKEMONS,
    GET_POKEMON_BY_NAME,
    GET_POKEMON_BY_ID,
    GET_TYPES,
    POST_POKEMON,
    RESET,
    FILTER,
    SORT_NAME,
    SORT_ATTACK,
    SET_CURRENT_PAGE,
    SET_ERROR,
    CLEAR_ERROR,
    CLEAR_SUCCES
}