const GET_POKEMONS = 'GET_POKEMONS'
const GET_POKEMON_BY_NAME = 'GET_POKEMON_BY_NAME'
const GET_POKEMON_BY_ID = 'GET_POKEMON_BY_ID'
const GET_TYPES = 'GET_TYPES'
const RESET = 'RESET'
const FILTER_TYPE = 'FILTER_TYPE' 
const FILTER_FROM = 'FILTER_FROM'
const SORT_NAME = 'SORT_NAME'
const SORT_ATTACK = 'SORT_ATTACK'
const SET_ERROR = 'SET_ERROR'
const CLEAR_ERROR = 'CLEAR_ERROR'

export {
    GET_POKEMONS,
    GET_POKEMON_BY_NAME,
    GET_POKEMON_BY_ID,
    GET_TYPES,
    RESET,
    FILTER_TYPE,
    FILTER_FROM,
    SORT_NAME,
    SORT_ATTACK,
    SET_ERROR,
    CLEAR_ERROR
}